characters/urls.py
from django.urls import path, include
from django.conf.urls import url
from .import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'characters'

urlpatterns = [
#    path('show/', views.show_characters, name='show_characters'),
    url(r'^comments/(?P<fk>[0-9]+)/$', views.character_comments, name="character_comments"),
    url(r'^vote/(?P<fk>[0-9]+)/$', views.vote_character, name='vote_character'),
    path('comments/', include('comments.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'comments'

urlpatterns = [
    url(r'^/(?P<pk>[0-9]+)/comment', views.comment_character, name="comment_character"),
]

votelly/urls.py
from django.contrib import admin
from django.urls import path, include
from programs import views as program_views
from characters import views as character_views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', program_views.home, name='home'),
    path('disclaimer/', program_views.disclaimer, name='disclaimer'),
    url(r'^program/(?P<fk>[0-9]+)/$', program_views.program_characters, name="program_characters"),
    path('characters/', include('characters.urls')),
    path('characters/comments', include('comments.urls')),
    # REST url
    url(r'^api/programs/$', program_views.program_list),
    url(r'^api/characters/$', character_views.character_list),
    url(r'^api/characters/(?P<pk>[0-9]+)$', character_views.character_detail),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
from django.db import models
from characters.models import Character

# Create your models here.
class Comment(models.Model):
    comment_text = models.CharField(max_length=250)
    comment_time = models.DateTimeField()
    related_character = models.ForeignKey(Character, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.comment_text[:100]

comments/views.py
from django.shortcuts import render, redirect
from .models import Comment
from programs.models import Program
from characters.models import Character
from django.utils import timezone
from django.http import HttpResponseRedirect

# Create your views here.
def comment_character(request, pk):
     if request.method == 'POST':
         comment = Comment()
         character = Character.objects.get(pk=pk)
         characters = Character.objects.filter(related_program = character.related_program).order_by('-number_of_votes')
         program = character.related_program
         total_votes = max_votes(characters)
         comment.comment_text = request.POST['comment_text']
         comment.comment_time = timezone.datetime.now()
         comment.related_character = character
         comment.save()
#         character.number_of_votes += 1
#         character.save()
         comments = Comment.objects.filter(related_character_id = pk).order_by('-comment_time')[0:20]
         template_path = 'comments/comment.html'
         context_dictionary = {'comments':comments, 'program':program, 'characters':characters, 'total_votes':total_votes}
         return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def max_votes(chars):
    max_votes = 0
    for character in chars:
        if character.number_of_votes > max_votes:
            max_votes = character.number_of_votes
    return(max_votes)

comments/templates/comments/comment.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <h1 class="my-4">
    <a href="{% url 'program_characters' program.id %}">{{ program.name }}
    </a>
  </h1>
  
  <p>{{ program.vote_question }}</p>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Nimi</th>
        <th scope="col">Ääniä yhteensä</th>
      </tr>
    </thead>
    
    {% for character in characters.all %}
    <tbody>
      <tr>
        <th><a href="{% url 'characters:character_comments' character.id %}">{{ character.name }}</th></a>
        <th><div class="progress-bar progress-bar bg-danger" role="progressbar" style="width: {% widthratio character.number_of_votes max_votes 100 %}%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">{% widthratio character.number_of_votes total_votes 100 %}%</div></th>
      </tr>
    </thead>
    {% endfor %}
  
  </table>
  
  <h2>{{ character.name }}</h2>
  <div class="card card-outline-secondary my-4">
    <div class="card-header">
      <form method="POST" action="{% url 'comments:comment_character' character.id %}">
        {% csrf_token %}
        <div class="row">
          <div class="col-sm-7"><input type="text" class="form-control" id="formGroupExampleInput" placeholder="Kommentti" name="comment_text"></div>
          <div class=col-sm><input class="btn btn-success" type="submit" value="Kommentoi"></div>
        </div>
      </form>
    </div>
    
    <div class="card-body">
      {% for comment in comments.all %}
      <p>{{ comment.comment_text }}</p>
      <small class="text-muted">{{ comment.comment_time }}</small>
      <hr>
      {% endfor %}
    </div>
    
  </div>
</div>

{% endblock %}

comments/templates/comments/comments.html
{% extends 'base.html' %}
{% block content %}

{% for comment in comments.all %}
  {{ comment.comment_text }}
  <br>
  {{ comment.comment_time }}
{% endfor %}

{% endblock %}