characters/urls.py
from django.urls import path, include
from django.conf.urls import url
from .import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'characters'

urlpatterns = [
#    path('show/', views.show_characters, name='show_characters'),
    url(r'^comments/(?P<fk>[0-9]+)/$', views.character_comments, name="character_comments"),
    url(r'^vote/(?P<fk>[0-9]+)/$', views.vote_character, name='vote_character'),
    path('comments/', include('comments.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

votelly/urls.py
from django.contrib import admin
from django.urls import path, include
from programs import views as program_views
from characters import views as character_views
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', program_views.home, name='home'),
    path('disclaimer/', program_views.disclaimer, name='disclaimer'),
    url(r'^program/(?P<fk>[0-9]+)/$', program_views.program_characters, name="program_characters"),
    path('characters/', include('characters.urls')),
    path('characters/comments', include('comments.urls')),
    # REST url
    url(r'^api/programs/$', program_views.program_list),
    url(r'^api/characters/$', character_views.character_list),
    url(r'^api/characters/(?P<pk>[0-9]+)$', character_views.character_detail),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

characters/models.py
from django.db import models
from programs.models import Program

# Create your models here.
class Character(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    number_of_votes = models.IntegerField(default=0)
    related_program = models.ForeignKey(Program, on_delete=models.CASCADE, default=1)
    character_photo = models.ImageField(upload_to='media/', blank=True)
    image_alt_text = models.CharField(max_length=200)

    def __str__(self):
        return self.name[:100]

characters/views.py
from django.shortcuts import render
from characters.models import Character
from comments.models import Comment
from programs.models import Program

from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status
from rest_framework.decorators import api_view
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .serializers import *

# Add POST if add is applied
@api_view(['GET'])
def character_list(request):
    if request.method == 'GET':
        data = []
        nextPage = 1
        previousPage = 1
        characters = Character.objects.all()
        page = request.GET.get('page', 1)
        paginator = Paginator(characters, 10)
        try:
            data = paginator.page(page)
        except PageNotAnInteger:
            data = paginator.page(1)
        except EmptyPage:
            data = paginator.page(paginator.num_pages)
        
        serializer = CharacterSerializer(data,context={'request': request} ,many=True)
        if data.has_next():
            nextPage = data.next_page_number()
        if data.has_previous():
            previousPage = data.previous_page_number()
        
        return Response({'data': serializer.data , 'count': paginator.count, 
        'numpages' : paginator.num_pages, 'nextlink': '/api/characters/?page=' + str(nextPage), 
        'prevlink': '/api/characters/?page=' + str(previousPage)})

@api_view(['PUT'])
def character_detail(request, pk):
    try:
        characters = Character.objects.get(pk=pk)
    except Character.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'PUT':
        serializer = CharacterSerializer(characters, data=request.data,context={'request': request})
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


def character_comments(request, fk):
    comments = Comment.objects.filter(related_character_id = fk).order_by('-comment_time')[0:20]
    character = Character.objects.filter(id=fk).first()
    characters = Character.objects.filter(related_program = character.related_program).order_by('-number_of_votes')
    program = character.related_program
    total_votes = total_character_votes(characters)
    max_votes = max_character_votes(characters)
    template_path = 'comments/comment.html'
    context_dictionary = {'comments':comments, 'program':program, 'character':character, 'characters':characters, 'total_votes':total_votes, 'max_votes':max_votes}
    return render(request, template_path, context_dictionary)

def vote_character(request, fk):
     if request.method == 'POST':
#         comment = Comment()
         character = Character.objects.get(pk=fk)
         characters = Character.objects.filter(related_program = character.related_program).order_by('-number_of_votes')
         program = character.related_program
#         comment.comment_text = request.POST['comment_text']
#         comment.comment_time = timezone.datetime.now()
#         comment.related_character = character
#         comment.save()
         character.number_of_votes += 1
         character.save()
         total_votes = total_character_votes(characters)
         max_votes = max_character_votes(characters)
         comments = Comment.objects.filter(related_character_id = fk).order_by('-comment_time')[0:20]
         template_path = 'comments/comment.html'
         context_dictionary = {'comments':comments, 'program':program, 'character':character, 'characters':characters, 'total_votes':total_votes, 'max_votes':max_votes}
         return render(request, template_path, context_dictionary)

def total_character_votes(chars):
    total = 0
    for character in chars:
        total = total + character.number_of_votes
    return(total)

def max_character_votes(chars):
    maximum = 0
    for character in chars:
        if character.number_of_votes > maximum:
            maximum = character.number_of_votes
    return(maximum)

characters/templates/characters/vote.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <h1 class="program--name">{{ program.first.name }}</h1>
  <p class="program--vote-question">{{ program.first.vote_question }}</p>
  <h2 class="program--participants">Osallistujat</h2>
</div>

{% for character in characters.all %}
<div class="col-lg-4 col-sm-6 text-center mb-4">
  <img class="rounded-circle img-fluid d-block mx-auto" src="{{ character.character_photo.url }}" alt="{{ character.image_alt_text }}" title="{{ character.image_alt_text }}">
  <h3><a href="{% url 'characters:character_comments' character.id %}">{{ character.name }}</h3></a>
  <p>{{ character.description }}</p>
  <form method="POST" action="{% url 'characters:vote_character' character.id %}">
    {% csrf_token %}
    <th><input class="btn btn-success" type="submit" value="Äänestä"></th>
  </form>
</div>
{% endfor %}

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Nimi</th>
      <th scope="col">Ääniä yhteensä</th>
    </tr>
  </thead>
  
  {% for character in characters.all %}
  <tbody>
    <tr>
      <th><a href="{% url 'characters:character_comments' character.id %}">{{ character.name }}</th></a>
      <th>
        <div class="progress-bar progress-bar bg-danger" role="progressbar" 
        style="width: {% widthratio character.number_of_votes max_votes 100 %}%;" aria-valuenow="25" 
        aria-valuemin="0" aria-valuemax="100">{% widthratio character.number_of_votes total_votes 100 %}%</div></th>
    </tr>
  </thead>
  {% endfor %}  
</table>

{% endblock %}